task2 : BufferManager.cpp BufferReplacement.cpp BufferManager.hpp BufferFrame.hpp BufferReplacement.hpp
	g++ -std=c++11 -pthread -g -Wall -O0 -fsanitize=address buffertest.cpp BufferManager.cpp BufferReplacement.cpp -o task2 -march=native
